In [2]:
import pandas as pd
import pickle

In [3]:
## read in our pickle file!
filename = open('final_model.pkl', 'rb')

In [4]:
## instantiate the trained model
model = pickle.load(filename)

In [5]:
# don't forget to close pickle!
filename.close()

### generate some fake data
Let's pretend it's 1956

#### Mickey Mantle

In [16]:
# actual stats:
Runs = 132
AtBat = 533
Hits = 188
HmRun = 52
RBI = 130
Walks = 112

In [25]:
# turn those stats into a 2d numpy array
mickeymantle = [[AtBat, Hits, HmRun, RBI, Walks]]

In [26]:
# read in our pickled scaler
filename = open('fitted_scaler.pkl', 'rb')
myscaler = pickle.load(filename)
filename.close()

In [29]:
#  transform the data to the new parameters
scaled_mickey = myscaler.transform(mickeymantle)
scaled_mickey

array([[0.99284987, 1.87516974, 4.74150961, 3.13753823, 3.39066855]])

In [28]:
# how many runs do we predict that mickey got?
model.predict(scaled_mickey)

array([124.15446028])

In [30]:
# if we had NOT scaled, then our prediction would be meaningless!
model.predict(mickeymantle)

array([5050.88687541])